source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JSONViewControllers_Example' do
    pod 'JSONViewControllers', :path => '..'

    target 'JSONViewControllers_Tests'  do
      inherit! :search_paths

      pod 'Quick', '~> 0.8.0'
      pod 'Nimble', '3.0.0'
      pod 'FBSnapshotTestCase'
      pod 'Nimble-Snapshots'
    end
end
